package Calcul;

/**
* Calcul/calcul_montantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* Monday, December 5, 2022 9:25:30 PM CET
*/

public final class calcul_montantsHolder implements org.omg.CORBA.portable.Streamable
{
  public Calcul.calcul_montants value = null;

  public calcul_montantsHolder ()
  {
  }

  public calcul_montantsHolder (Calcul.calcul_montants initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calcul.calcul_montantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calcul.calcul_montantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calcul.calcul_montantsHelper.type ();
  }

}
