package Calcul;


/**
* Calcul/calcul_montants.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* Monday, December 5, 2022 9:25:30 PM CET
*/

public interface calcul_montants extends calcul_montantsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul_montants
