package Calcul;


/**
* Calcul/calcul_montantsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* Monday, December 5, 2022 9:25:30 PM CET
*/

public interface calcul_montantsOperations 
{
  double calcul_ttc (double ht, double tva);
} // interface calcul_montantsOperations
